# Generated by Django 6.0.3 on 2026-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='note',
            name='is_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Untitled Note', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prayer',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prayer',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
