# Generated by Django 6.0.3 on 2026-04-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_note_is_task_task_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_completed', '-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
