# Generated by Django 6.0.3 on 2026-05-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fastinglog_finance_habitlog_alter_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoCAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('town_hall_level', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_number', models.IntegerField()),
                ('is_bob', models.BooleanField(default=False)),
                ('current_task', models.CharField(blank=True, max_length=200)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('is_free', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cocaccount')),
            ],
        ),
    ]
